Added Deep Learning CNN to extract texts from images
AnirudhMergu/TesseractOCR pull request #1
Opened 2020-10-01 21:13 UTC by malikakarsh

Hey dude try this out. I have added a deep learning script to extract text from images

2020-10-02 02:10 UTC, AnirudhMergu commented
@malikakarsh Thanks for the pull request! This PR has so many changes, can you add more details on how to run this and how you have tested them. It would be great if you provide more details so that people can understand things  easily.

Thanks again,
Anirudh

2020-10-02 07:43 UTC, malikakarsh commented
Sure, I would add an additional readme.md file by today itself!

On Fri, 2 Oct 2020, 07:40 Anirudh Sai Mergu, <notifications@github.com>
wrote:

> @malikakarsh <https://github.com/malikakarsh> Thanks for the pull
> request! This PR has so many changes, can you add more details on how to
> run this and how you have tested them. It would be great if you provide
> more details so that people can understand things easily.
>
> Thanks again,
> Anirudh
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/AnirudhMergu/TesseractOCR/pull/1#issuecomment-702489084>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APAUOWUWJFONHWIRACXJ72LSIUZAVANCNFSM4SA6EP5Q>
> .
>

2020-10-02 07:49 UTC, malikakarsh commented
> @malikakarsh Thanks for the pull request! This PR has so many changes, can you add more details on how to run this and how you have tested them. It would be great if you provide more details so that people can understand things easily.
> 
> Thanks again,
> Anirudh

Instead of using pytesseract I have actually made a model that works similar to it using deep learning and opencv to extract texts from images. This will be of help to them who want to learn how pytesseract is able to extract texts from images!

2020-10-03 04:20 UTC, AnirudhMergu requested changes

2020-10-03 04:20 UTC, AnirudhMergu commented on README.md
> +Tesseract is an optical character recognition engine for various operating systems which extracts texts from an image and converts them to plain text.
Hey, do not remove the README contents. Just add incremental changes.

2020-10-03 05:19 UTC, malikakarsh commented
okay

On Sat, 3 Oct 2020, 09:50 Anirudh Sai Mergu, <notifications@github.com>
wrote:

> *@AnirudhMergu* requested changes on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/AnirudhMergu/TesseractOCR/pull/1#discussion_r499114448>
> :
>
> >
> -The written version of the tutorial is found at : https://blog.anirudhmergu.com/code/ocr-using-python-and-tesseract/
> +Tesseract is an optical character recognition engine for various operating systems which extracts texts from an image and converts them to plain text.
>
> Hey, do not remove the README contents. Just add incremental changes.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/AnirudhMergu/TesseractOCR/pull/1#pullrequestreview-501519527>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APAUOWWZX2LW2HGOPLKSEETSI2RBFANCNFSM4SA6EP5Q>
> .
>

2023-06-02 07:12 UTC, harindramittal commented
hi I found particular text compare to another column text

2026-04-28 22:59 UTC, closed without merging